# Generated by Django 3.2.12 on 2022-02-24 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=200)),
                ('image_description', models.CharField(max_length=3000)),
                ('date_added', models.DateField(auto_now=True)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.category')),
                ('location_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.location')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
    ]
